# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0002_auto_20171105_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
