# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0004_book_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
