# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0005_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='large_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='medium_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='small_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='tiny_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
