# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0006_auto_20171115_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='large_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='medium_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tiny_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
