# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0008_auto_20171119_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
